language: node_js
cache:
  directories:
    - $HOME/.mongodb-binaries
notifications:
  slack: theselftalk:EHiDWYYgq34Y172TrHTqA16W
node_js:
  - stable
install:
  - yarn install
script:
  - yarn lint
  - yarn run test-unit
  - yarn run test-integration
  - zip -qr course-manager.zip . -x *.git* node_modules/\*
deploy:
  provider: releases
  api_key: ${GITHUB_OAUTH_TOKEN}
  file: 'course-manager.zip'
skip_cleanup: true
