language: node_js
notifications:
  slack: theselftalk:EHiDWYYgq34Y172TrHTqA16W
node_js:
  - stable
# before_script:
#   - sudo apt-get install zip
#   - docker-compose -f docker-compose.test.yml up --build -d
#   - docker-compose logs mongosetup
#   - sh scripts/createSymlinks.sh
install:
  - yarn install
script:
  - yarn lint
  - yarn run test-unit
  - yarn run test-integration
  - zip -qr course-manager.zip . -x *.git* node_modules/\*
# after_success:
#   - yarn run coverage
deploy:
  provider: releases
  api_key: ${GITHUB_OAUTH_TOKEN}
  file: 'course-manager.zip'
skip_cleanup: true
